### ISSUE TITLE
setup.py stucks at "Installing Libraries...."

### ISSUE THREAD

**Issue by kaiyaf57** [Nyumat/The-TikTok-Bot#13]
@Nyumat 

setup.py stucks at "Installing Libraries...." - cant use your bot,  cant install depencies manually

**Comment by Nyumat** [comment]
Hello @kaiyaf57 , 

<b>setup.py is stuck</b> because `time.sleep(45)` is called inside the `installLibraries()` function . That's 100% my fault, I honestly didn't expect the packages to install in under 45 seconds. 😅 

Be sure to input `pip install os` into the command line before running `setup.py` as it is the only non-called module required.

Fix will be committed soon although **_keep in mind_,** requests-V1 is currently under maintenance and still being tinkered with for optimal functionality 👍🏿 .

If you want a tool that is in production _right now_, see below.

I <b>do not</b> condone the use/abuse of TikTok/Social Media exploits, but... 

[hm](vipto.de)
[hmm](mytoolstown.com)
[hmmm](fireliker.com)
[hmmmm](https://www.instafollowers.co/free-tiktok-likes) 

Maybe if enough people email me, I'll at least _think_ about building another simple selenium script. It would likely be reminiscent of `autoViews.py` and would automatically crawl those referenced services for you.
